title:              Print or Echo
email:              s.m.shahinul.islam@gmail.com
description:        by S M Shahinul Islam
author:             S M Shahinul Islam
baseurl:            "/"
url:                "https://imshahinul.github.io"

# Social Profiles
#twitter_username:   SBootstrap
github_username:    imshahinul
#facebook_username:  StartBootstrap
#instagram_username:
linkedin_username: shahinulislam

# Add your google-analytics ID here to activate google analytics
google_analytics:   G-18P0G4M471 # out your google-analytics code

# Build settings
markdown:           GFM
paginate:           10
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
  - jekyll-seo-tag
